CREATE ROLE root WITH PASSWORD 'password';
ALTER ROLE root WITH LOGIN;
CREATE DATABASE keycloak;
CREATE DATABASE launchobject;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO root;
GRANT ALL PRIVILEGES ON DATABASE launchobject TO root;
